apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-guestbook-deployment
  labels:
    app: guestbook-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: front-end-guestbook-pod
      app: guest-app
  template:
    metadata:
      name:  front-end-guestbook-pod
      labels:
        name: front-end-guestbook-pod
        app: guestbook-app
    spec:
      containers:
      - name: guestbook
        image: kubernetes/guestbook:v2
        ports:
        - containerPort: 80