apiVersion: v1
kind: Service
metadata:
  name: front-end-guestbook-service
  labels:
    name: front-end-guestbook-service
    app: guestbook-app
spec:
  type: nodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: front-end-guestbook-pod
    app: guestbook-app